### ISSUE TITLE
[Feature] Option to output mask in Y8

### ISSUE THREAD

**Issue by Purfview** [Asd-g/AviSynth-tcolormask#1]
Could be there option to output mask in Y8?

**Comment by Asd-g** [comment]
Ok.

**Comment by Asd-g** [comment]
You can try 1.2.1.

**Comment by Purfview** [comment]
Thx, I'll try it asap.

**Comment by Purfview** [comment]
Tested, everything works as expected and faster than before.
Thank you very much!
